$(document).ready(function () {
  function getRequest() {
  //   templateString = `<div class="card h-100 shadow card-span p-3">
  //   <div class="card-body">
  //     <div class="d-flex align-items-center">
  //     <img class="img-fluid" src="assets/img/gallery/user-3.png" alt="testimonials">
  //       <div class="flex-1 ms-4">
  //         <h6 class="fw-light fs-lg-1 mb-1">{Niek Bove}</h6>
  //         <p class="fw-normal mb-0 text-800">{Senior Developer}</p>
  //       </div>
  //     </div>
  //     <p class="mb-0 mt-4 fw-light lh-lg">
  //     Nisi cumque in necessitatibus molestiae eaque excepturi ab. Laboriosam ipsam voluptatem voluptatibus labore quam nihil. Quasi occaecati quos ratione quia aut molestiae velit et.</p>
  //   </div>
  // </div>`;
  templateString = `
  <div class='row'>
  <h2 class="title-page detail">Showbiz 8 - siêu mẫu Thanh Hằng: "Tôi không đặt nặng kinh tế với bạn trai"</h2>
  <div class="text-center">
    <img src="https://th.bing.com/th/id/OIP.4g9-yIBm-G56rSlQAEFp6AHaE9?pid=ImgDet&rs=1" class="rounded mx-auto d-block img-fluid" alt="Responsive image">
  </div>
  <p></p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  <p>Trước ý kiến này, Hồ Ngọc Hà đã có những chia sẻ thẳng thắn với phóng viên <em>Dân trí</em>: "Cả tôi và Thanh Hằng đều không có thời gian để đi chứng minh tình bạn cho mọi người thấy. Ai cũng có cuộc sống riêng, gọi là "thân nhất trong showbiz" cũng đúng vì cứ cần, gọi sẽ có mặt nhưng không phải ngày nào chúng tôi cũng gặp hoặc lắng nghe và chia sẻ hết những chuyện riêng tư về nhau. Chúng tôi là những người tôn trọng, ngưỡng mộ và luôn giúp đỡ nhau trong công việc. Tôi thấy đó là một điều đáng quý".</p>
  </div>
  `


    
    return templateString
  }

  $('#btnSaveChange').click(function() {
    setTimeout(() => {
      $('#bodyContentPost').html(getRequest());
    }, 1500);
  })


});



